version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g typescript
      - npm install -g aws-cdk
  build:
    commands:
      - npm ci
      - npm run build
      - cdk deploy
