name: blog-backend-infrastructure
description: AWS resources related with my personal blog
environment: prd
gitRepository: https://github.com/alazaroc/blog-backend-infrastructure
resources:
  ssm:
    personalEmail: personal-email
    gitHubRepository: connection-github-alazaroc
    blogCertificateArn: /blog/certificate-arn
  lambda:
    contact:
      memorySize: 128
    subscription:
      memorySize: 128
    comment:
      memorySize: 128
  s3:
    cicd: codepipeline-artifact
