description: AWS resources related with my personal blog
environment: prd
resources:
  ssm:
    personalEmail: personal-email
  lambda:
    contact:
      memorySize: 128
    subscription:
      memorySize: 128
    comment:
      memorySize: 128
