name: blog-backend-infrastructure
description: AWS resources related with my personal blog
environment: prd
gitRepository: https://github.com/alazaroc/blog-backend-infrastructure
resources:
  ssm:
    personalEmail: /general/data/personal-email
    gitHubRepository: /general/codestar/github-connect
    snsFinalNotifications: /general/sns/final-notifications
    snsFormatPipeline: /general/sns/format-codepipeline
    blogCertificateArn: /blog/certificate-arn
  lambda:
    contact:
      memorySize: 128
    subscription:
      memorySize: 128
    comment:
      memorySize: 128
  s3:
    cicd: codepipeline-artifact
